// Code generated by Slice Machine. DO NOT EDIT.

import Accordion from "./Accordion/index.svelte";
import CaseStudy from "./CaseStudy/index.svelte";
import ContentWidthMedia from "./ContentWidthMedia/index.svelte";
import CtaBanner from "./CtaBanner/index.svelte";
import FeaturedProject from "./FeaturedProject/index.svelte";
import IndustryHero from "./IndustryHero/index.svelte";
import LeadText from "./LeadText/index.svelte";
import LogoGrid from "./LogoGrid/index.svelte";
import RichText from "./RichText/index.svelte";
import ScreenWidthColumns from "./ScreenWidthColumns/index.svelte";
import ScreenWidthMedia from "./ScreenWidthMedia/index.svelte";
import Slideshow from "./Slideshow/index.svelte";
import Testimonial from "./Testimonial/index.svelte";
import TextColumns from "./TextColumns/index.svelte";
import ValueBlock from "./ValueBlock/index.svelte";

export const components = {
  accordion: Accordion,
  case_study: CaseStudy,
  content_width_image: ContentWidthMedia,
  cta_banner: CtaBanner,
  featured_project: FeaturedProject,
  industry_hero: IndustryHero,
  lead_text: LeadText,
  logo_grid: LogoGrid,
  rich_text: RichText,
  screen_width_columns: ScreenWidthColumns,
  screen_width_image: ScreenWidthMedia,
  slideshow: Slideshow,
  testimonial: Testimonial,
  text_columns: TextColumns,
  value_block: ValueBlock,
};
