// Code generated by Slice Machine. DO NOT EDIT.

import Accordion from "./Accordion/index.svelte";
import ContentWidthMedia from "./ContentWidthMedia/index.svelte";
import LeadText from "./LeadText/index.svelte";
import RichText from "./RichText/index.svelte";
import ScreenWidthColumns from "./ScreenWidthColumns/index.svelte";
import ScreenWidthMedia from "./ScreenWidthMedia/index.svelte";
import Slideshow from "./Slideshow/index.svelte";
import TextColumns from "./TextColumns/index.svelte";
import ValueBlock from "./ValueBlock/index.svelte";

export const components = {
  accordion: Accordion,
  content_width_image: ContentWidthMedia,
  lead_text: LeadText,
  rich_text: RichText,
  screen_width_columns: ScreenWidthColumns,
  screen_width_image: ScreenWidthMedia,
  slideshow: Slideshow,
  text_columns: TextColumns,
  value_block: ValueBlock,
};
