import type { AuditReport } from "../fetch";

/**
 * A complete stored result in which every stage ran and nothing failed.
 *
 * This is the "check, check, check" page: the shape the report takes when a
 * site is doing everything we can measure. It exists because a report that
 * can only ever render findings has no way to say "this is right", and we
 * want our own site to reach this page — it is not there yet, which is why it
 * is a test case rather than the fixture.
 *
 * The business is fictional and the URL is on a reserved TLD, so nothing here
 * can be mistaken for a client. Rendered at /dev/audit-report, and asserted
 * all-clear end to end in narrative.test.ts.
 */
const URL = "https://example-studio.test/";
const PAGES = ["/", "/work", "/about", "/services", "/contact"].map(
  (p) => `${URL.slice(0, -1)}${p}`,
);

const question = (question: string, evidence: string) => ({
  question,
  answered: "yes" as const,
  quotable: true,
  page: `${URL}services`,
  evidence,
});

const requirement = (
  key: string,
  label: string,
  evidence: string,
  why: string,
  scope: "quick" | "content" | "structural",
) => ({
  key,
  label,
  status: "met" as const,
  evidence,
  why,
  scope,
});

const assertion = (claim: string, engineQuote: string, siteQuote: string) => ({
  claim,
  verdict: "confirmed" as const,
  engineQuote,
  siteQuote,
  unverifiedReason: null,
  nearbyMention: null,
  sourceDomains: ["example-studio.test", "linkedin.com"],
  query: "who is Example Studio",
  engine: "claude",
});

export const ALL_PASS_REPORT: AuditReport = {
  url: URL,
  businessName: "Example Studio",
  generatedAt: "2026-09-03T09:00:00.000Z",
  // What computeScores (reddoor-maintenance src/prospect/checks.ts) gives a
  // perfect site: findability and readability are deterministic and reach 100
  // (the scorer's own test pins this); answers is ten of ten; visibility is a
  // measurement, not a score, and one of two searches named the site.
  scores: { findability: 100, readability: 100, answers: 100, aiVisibility: 50 },
  crawl: {
    ok: true,
    data: {
      agentAccess: [
        "GPTBot",
        "ClaudeBot",
        "PerplexityBot",
        "Google-Extended",
        "Bytespider",
        "CCBot",
        "anthropic-ai",
        "Applebot-Extended",
      ].map((agent) => ({ agent })),
    },
  },
  checks: {
    ok: true,
    data: {
      crawlerAccessMeasured: true,
      crawlerAccess: { blockedAi: [], blockedClassical: [] },
      viewportOk: true,
      journey: {
        affordances: [
          { kind: "form", page: `${URL}contact`, detail: "enquiry form with 6 fields" },
          { kind: "tel", page: URL, detail: "tel:+15125550142" },
        ],
        pages: PAGES.map((url) => ({ url, clicksToContact: 0, internalLinks: 12 })),
        deadEnds: [],
        worstClicksToContact: 0,
        pagesExamined: PAGES.length,
      },
      consistency: {
        phones: [
          { normalized: "+15125550142", seenAs: ["(512) 555-0142"], pages: PAGES, linked: true },
        ],
        emails: [
          {
            normalized: "hello@example-studio.test",
            seenAs: ["hello@example-studio.test"],
            pages: PAGES,
            linked: true,
          },
        ],
        copyrightYears: [2026],
        newestCopyrightYear: 2026,
        pagesOffTemplate: [],
        sharedNavLinks: 5,
        pagesExamined: PAGES.length,
      },
    },
  },
  assets: {
    ok: true,
    data: {
      brokenLinks: [],
      brokenImages: [],
      heaviestImages: [],
      imageBytesMeasured: 2_400_000,
      imagesWithKnownSize: 18,
      linksFound: 64,
      linksChecked: 64,
      imagesFound: 18,
      imagesChecked: 18,
    },
  },
  // Real numbers, measured by running axe over our own report page rather than
  // invented: the default rule set is 90 rules, of which 42 had something to
  // check and passed, 47 had nothing on the page to apply to, and one needed a
  // human. An all-pass site has no violations — and the section still has to
  // say plainly that a clean automated scan is a floor, not a verdict.
  accessibility: {
    ok: true,
    data: {
      measured: true,
      pagesExamined: 5,
      rulesPassed: 42,
      rulesIncomplete: 1,
      rulesInapplicable: 47,
      violations: [],
      violationsTotal: 0,
    },
  },
  // The whole check battery, GENERATED by running the real `runSiteChecks`
  // over an exemplary crawl rather than written by hand — a hand-written
  // all-pass fixture drifts out of reach of the checks and then passes forever
  // while proving nothing. Doing it this way has already caught two real
  // instrument bugs.
  //
  // Three land as not-applicable, which is the fourth state earning its keep:
  // this site publishes no rating markup, no language alternates, and no link
  // that opens a new tab. None of those is a pass, and none is counted.
  siteChecks: {
    ok: true,
    data: [
      {
        key: "dead-links",
        label: "Links that go nowhere",
        status: "pass",
        evidence: "none among the 15 links we read",
        why: "A link that goes nowhere reads as a broken site to the person who clicks it.",
        scope: "quick",
      },
      {
        key: "staging-links",
        label: "Links pointing at a development address",
        status: "pass",
        evidence: "none",
        why: "A link to localhost or a staging host takes the visitor to a browser error page with your name on it.",
        scope: "quick",
      },
      {
        key: "insecure-links",
        label: "Links that drop out of https",
        status: "pass",
        evidence: "every link stays on https",
        why: "A link back to plain http shows a “not secure” warning on a site that had earned the padlock.",
        scope: "quick",
      },
      {
        key: "link-text",
        label: "Links that say where they go",
        status: "pass",
        evidence: "all 15 links we read name their destination",
        why: "“Read more” tells a visitor nothing, and it is the whole label a screen reader announces when it lists the links on your page.",
        scope: "content",
      },
      {
        key: "tel-dialable",
        label: "Phone links a phone can dial",
        status: "pass",
        evidence: "all 5 dial a number",
        why: "A tel: link that is not a number does nothing at all when it is tapped.",
        scope: "quick",
      },
      {
        key: "social-placeholders",
        label: "Social links that go to your accounts",
        status: "pass",
        evidence: "none left unedited",
        why: "An unedited theme placeholder sends a visitor to a login page or to somebody else entirely.",
        scope: "quick",
      },
      {
        key: "nav-consistency",
        label: "Navigation that agrees with itself",
        status: "pass",
        evidence: "2 shared menu items go to the same place on every page",
        why: "The same menu item leading to two different pages is the kind of confusion visitors blame on you rather than on the menu.",
        scope: "quick",
      },
      {
        key: "lorem",
        label: "Placeholder Latin left in the copy",
        status: "pass",
        evidence: "none across the 5 pages we read",
        why: "Lorem ipsum on a live page tells a visitor the site was never finished.",
        scope: "quick",
      },
      {
        key: "placeholder-copy",
        label: "Theme placeholder text left in the copy",
        status: "pass",
        evidence: "none across the 5 pages we read",
        why: "“Your text here” on a live page reads as a site nobody has looked at since it was built.",
        scope: "quick",
      },
      {
        key: "template-leakage",
        label: "Template code showing as text",
        status: "pass",
        evidence: "none across the 5 pages we read",
        why: "A visitor sees the machinery instead of the sentence, which reads as broken rather than unfinished.",
        scope: "quick",
      },
      {
        key: "mojibake",
        label: "Text with broken characters",
        status: "pass",
        evidence: "none across the 5 pages we read",
        why: "Apostrophes and quotes rendering as â€™ is the most visible sign of a migration nobody checked, and it is a one-line fix at the source.",
        scope: "quick",
      },
      {
        key: "under-construction",
        label: "Pages that say they are unfinished",
        status: "pass",
        evidence: "none across the 5 pages we read",
        why: "A live page announcing it is coming soon is a page better unlinked until it is not.",
        scope: "content",
      },
      {
        key: "name-in-title",
        label: "Your name in the page title",
        status: "pass",
        evidence: "“Example Studio — Brand and Website Design in Austin”",
        why: "The title is the line in a search result, a browser tab and a shared link. Without your name in it, all three are anonymous.",
        scope: "quick",
      },
      {
        key: "single-h1",
        label: "One headline per page",
        status: "pass",
        evidence: "all 5 pages carry exactly one",
        why: "The h1 is the page's headline. None leaves a reader — and an assistant — guessing what the page is about; several means none of them is.",
        scope: "content",
      },
      {
        key: "h1-not-name",
        label: "Headlines that say what the page is about",
        status: "pass",
        evidence: "every headline describes its page",
        why: "A headline that is only your company name describes none of the page below it.",
        scope: "content",
      },
      {
        key: "h1-distinct",
        label: "A different headline on each page",
        status: "pass",
        evidence: "5 pages, 5 different headlines",
        why: "Identical headlines make every page look like the same page, to a reader scanning tabs and to a search engine choosing which one to show.",
        scope: "content",
      },
      {
        key: "schema-org-complete",
        label: "Your business details in structured data",
        status: "pass",
        evidence: "name, url and logo all present on your LocalBusiness block",
        why: "This is the block an assistant reads to learn who you are. Half-filled, it answers half the question and the rest gets taken from a directory you do not control.",
        scope: "content",
      },
      {
        key: "schema-local-complete",
        label: "Your address and hours in structured data",
        status: "pass",
        evidence: "address, telephone and opening hours all present",
        why: "A local business block without an address, a phone or opening hours is the one an assistant will fill in from elsewhere.",
        scope: "content",
      },
      {
        key: "schema-url-matches",
        label: "Structured data pointing at this site",
        status: "pass",
        evidence: "https://example-studio.test",
        why: "A structured-data url pointing at a domain you no longer use tells every assistant that reads it to go and look somewhere else.",
        scope: "content",
      },
      {
        key: "schema-phone-matches",
        label: "One phone number, everywhere",
        status: "pass",
        evidence: "(512) 555-0142, matching the page",
        why: "When the number in your structured data is not the number on your page, an assistant may quote either one.",
        scope: "quick",
      },
      {
        key: "schema-self-review",
        label: "Ratings you publish about yourself",
        status: "not-applicable",
        evidence: "no review or rating markup on this site",
        why: "Google does not show star ratings a business publishes about itself, so the markup does nothing but sit there.",
        scope: "content",
      },
      {
        key: "meta-noindex",
        label: "Pages search engines are allowed to list",
        status: "pass",
        evidence: "none of the 5 pages we read asks to be hidden",
        why: "This one line tells every search engine and assistant to leave the page out of their results entirely. It is almost always left over from a staging site, and nothing on the page looks wrong.",
        scope: "quick",
      },
      {
        key: "meta-nofollow",
        label: "Links search engines are allowed to follow",
        status: "pass",
        evidence: "no page-wide nofollow",
        why: "It tells search engines not to follow any link on the page, so nothing you link to gets credit from it.",
        scope: "quick",
      },
      {
        key: "meta-charset",
        label: "A declared character set",
        status: "pass",
        evidence: "declared on all 5 pages",
        why: "Without a declared character set the browser guesses, and a wrong guess is what turns apostrophes into â€™.",
        scope: "quick",
      },
      {
        key: "title-length",
        label: "Titles that survive a search result",
        status: "pass",
        evidence: "all 5 are between 10 and 70 characters",
        why: "A title that is too long is cut off mid-word in the result, and one that is too short wastes the most valuable line you get.",
        scope: "content",
      },
      {
        key: "description-length",
        label: "Descriptions that survive a search result",
        status: "pass",
        evidence: "all 5 are between 50 and 170 characters",
        why: "The description is the sentence under your link. Too long and it is truncated; too short and the engine writes its own.",
        scope: "content",
      },
      {
        key: "og-image-absolute",
        label: "A share image that loads anywhere",
        status: "pass",
        evidence: "https://example-studio.test/og.jpg",
        why: "A relative og:image renders no card at all on Slack, LinkedIn or iMessage — the link arrives as bare text.",
        scope: "quick",
      },
      {
        key: "duplicate-descriptions",
        label: "A different description on each page",
        status: "pass",
        evidence: "5 pages, 5 different descriptions",
        why: "Identical descriptions make every page look like the same page in a search result, and the engine usually replaces them with a sentence of its own choosing.",
        scope: "content",
      },
      {
        key: "favicon-declared",
        label: "An icon for the browser tab",
        status: "pass",
        evidence: 'rel="icon" → /favicon.ico',
        why: "Without one the browser shows a blank page icon in the tab and the bookmark, which is the smallest possible thing to fix and the most often seen.",
        scope: "quick",
      },
      {
        key: "canonical-self",
        label: "Pages that point at themselves",
        status: "pass",
        evidence: "all 5 canonicals point at their own page",
        why: "A canonical pointing somewhere else tells search engines to index that page instead of this one. Every page pointing at the home page is the version of this mistake that removes a whole site from search results.",
        scope: "structural",
      },
      {
        key: "canonical-origin",
        label: "Canonicals that stay on your domain",
        status: "pass",
        evidence: "every canonical stays on this domain",
        why: "A canonical on another domain hands every page's search ranking to that domain. It is usually a staging host or a site they used to own.",
        scope: "structural",
      },
      {
        key: "hreflang-self",
        label: "Language alternates that name themselves",
        status: "not-applicable",
        evidence: "this site publishes no language alternates",
        why: "An hreflang set that does not name itself is ignored, so the translated pages compete with each other instead of being offered to the right reader.",
        scope: "content",
      },
      {
        key: "form-field-types",
        label: "Fields typed for a phone keyboard",
        status: "pass",
        evidence: "your email and phone fields use the right input types",
        why: "An email field typed as plain text gives a phone the ordinary keyboard, so the visitor hunts for the @ at exactly the moment they had decided to write to you.",
        scope: "content",
      },
      {
        key: "form-autocomplete",
        label: "Fields a phone can fill in one tap",
        status: "pass",
        evidence: "all 5 enquiry forms carry autocomplete",
        why: "With these, a phone offers to fill the whole form in one tap. Without them it does not offer at all.",
        scope: "content",
      },
      {
        key: "form-method",
        label: "A form that does not put answers in the URL",
        status: "pass",
        evidence: "every enquiry form posts",
        why: "A form that submits with GET puts everything the visitor typed into the address bar, and from there into your server logs and their browser history.",
        scope: "quick",
      },
      {
        key: "form-action",
        label: "A form that posts somewhere we recognise",
        status: "pass",
        evidence: "your forms post to your own site",
        why: "A form posting to an endpoint nobody owns any more looks like it worked and silently goes nowhere.",
        scope: "structural",
      },
      {
        key: "form-required",
        label: "Fields marked as required",
        status: "pass",
        evidence: "every enquiry form marks at least one field required",
        why: "Without it the browser cannot stop a half-filled form being sent, and the visitor finds out something was missing only if somebody tells them.",
        scope: "quick",
      },
      {
        key: "noopener",
        label: 'New-tab links carrying rel="noopener"',
        status: "not-applicable",
        evidence: "no link on these pages opens a new tab",
        why: 'Adding rel="noopener" to links that open a new tab is a one-line habit that keeps older browsers from handing the new page a reference back to yours.',
        scope: "quick",
      },
      {
        key: "header-strict-transport-security",
        label: "Telling browsers to always use https",
        status: "pass",
        evidence: "strict-transport-security is set",
        why: "Without it, the first visit of the day can still be made over plain http before the redirect happens.",
        scope: "quick",
      },
      {
        key: "header-content-security-policy",
        label: "A policy for what may run on your pages",
        status: "pass",
        evidence: "content-security-policy is set",
        why: "It is the difference between a compromised script running on your site and being blocked by the browser.",
        scope: "quick",
      },
      {
        key: "header-x-content-type-options",
        label: "Stopping browsers guessing file types",
        status: "pass",
        evidence: "x-content-type-options is set",
        why: "One line that prevents a browser treating an uploaded file as something executable.",
        scope: "quick",
      },
      {
        key: "header-x-frame-options",
        label: "Stopping other sites framing yours",
        status: "pass",
        evidence: "x-frame-options is set",
        why: "Without it, anyone can put your site inside theirs and collect what visitors type into it.",
        scope: "quick",
      },
      {
        key: "header-referrer-policy",
        label: "Controlling what you leak when visitors leave",
        status: "pass",
        evidence: "referrer-policy is set",
        why: "By default the full URL a visitor came from is handed to every site they click through to.",
        scope: "quick",
      },
      {
        key: "header-permissions-policy",
        label: "Declaring what your pages may ask for",
        status: "pass",
        evidence: "permissions-policy is set",
        why: "It stops an embedded third party quietly asking your visitors for their camera or location.",
        scope: "quick",
      },
      {
        key: "header-version-leak",
        label: "Not advertising your software versions",
        status: "pass",
        evidence: "no version numbers in your response headers",
        why: "Naming the exact version you run tells anyone looking which published vulnerabilities to try first.",
        scope: "quick",
      },
      {
        key: "header-compression",
        label: "Pages sent compressed",
        status: "pass",
        evidence: "content-encoding: br",
        why: "Uncompressed HTML is roughly four times the bytes for the same page, paid for by every visitor on a phone.",
        scope: "quick",
      },
      {
        key: "header-hsts-age",
        label: "An https policy that lasts",
        status: "pass",
        evidence: "max-age=31536000",
        why: "A max-age of a few minutes gives almost none of the protection the header exists for.",
        scope: "quick",
      },
      {
        key: "robots-not-blocking",
        label: "robots.txt not blocking your whole site",
        status: "pass",
        evidence: "nothing site-wide is disallowed",
        why: "A blanket Disallow tells every search engine and every assistant to stay off the whole site. It is usually left over from a staging server.",
        scope: "quick",
      },
      {
        key: "robots-names-sitemap",
        label: "robots.txt naming your sitemap",
        status: "pass",
        evidence: "a Sitemap: line is present",
        why: "Naming the sitemap in robots.txt is how a crawler that has never seen your site finds the list of your pages.",
        scope: "quick",
      },
      {
        key: "sitemap-coverage",
        label: "A sitemap that lists your pages",
        status: "pass",
        evidence: "12 URLs listed, against 2 distinct pages your own links point to",
        why: "A sitemap listing fewer pages than your own navigation links to leaves the rest to be found by luck.",
        scope: "content",
      },
      {
        key: "llms-txt",
        label: "A file written for AI assistants",
        status: "pass",
        evidence: "# Example Studio",
        why: "A short llms.txt is the one file that tells an assistant, in your words, what you do and which pages matter.",
        scope: "content",
      },
      {
        key: "analytics",
        label: "Something measuring whether any of this works",
        status: "pass",
        evidence: "https://plausible.io/js/script.js",
        why: "Without any analytics you cannot tell whether a change helped, which visit turned into an enquiry, or whether the work was worth doing.",
        scope: "quick",
      },
    ],
  },
  // The readout, not a check — nothing here passes or fails, so an "all pass"
  // fixture carries it for layout rather than for a verdict. A modern stack on
  // purpose: the section has to look right for a site doing everything well,
  // not only for the WordPress install it is most useful on.
  stack: {
    ok: true,
    data: {
      measured: true,
      pagesExamined: 5,
      headersExamined: true,
      items: [
        {
          layer: "framework",
          name: "SvelteKit",
          evidence: "https://example-studio.test/_app/immutable/entry/start.a1b2c3.js",
        },
        {
          layer: "forms",
          name: "Formspree",
          evidence: "https://formspree.io/f/xyzabc",
        },
        {
          layer: "analytics",
          name: "Plausible",
          evidence: "https://plausible.io/js/script.js",
        },
        {
          layer: "fonts",
          name: "Adobe Fonts (Typekit)",
          evidence: "https://use.typekit.net/abc1def.js",
        },
        { layer: "hosting", name: "Netlify", evidence: "x-nf-request-id header" },
      ],
    },
  },
  basics: {
    ok: true,
    data: {
      insecureEntry: {
        measured: true,
        url: "http://example-studio.test/",
        ok: true,
        landedOn: URL,
        error: null,
      },
      hostVariant: {
        measured: true,
        url: "https://www.example-studio.test/",
        host: "www.example-studio.test",
        ok: true,
        landedOn: URL,
        error: null,
      },
      notFound: {
        measured: true,
        url: `${URL}this-page-cannot-exist`,
        ok: true,
        landedOn: null,
        error: null,
        status: 404,
        linksBackToSite: true,
      },
      mixedContent: { measured: true, imageUrls: [], imagesSeen: 18 },
      altText: { imagesTotal: 18, imagesWithAlt: 18, pagesExamined: PAGES.length },
      duplicateTitles: [],
    },
  },
  goalFit: {
    ok: true,
    data: {
      goal: "enquire",
      source: "operator",
      requirements: [
        requirement(
          "qualifying-form",
          "A form that asks enough to have a real first conversation",
          "enquiry form with 6 fields",
          "A name-and-email box produces enquiries you have to qualify by hand.",
          "content",
        ),
        requirement(
          "route-to-contact",
          "A route to you from wherever they land",
          "every one of 5 pages links to /contact",
          "Search sends people to whichever page answers their question, not to the home page.",
          "quick",
        ),
        requirement(
          "price-signal",
          "Some signal of what it costs",
          "“Identity projects start at $12,000”",
          "Buyers ask this before making contact, and a site that does not answer it sends them to one that does.",
          "content",
        ),
        requirement(
          "what-happens-next",
          "What happens after they get in touch",
          "“We reply within one working day and book a 30-minute call”",
          "The last hesitation before the form is not knowing what the form starts.",
          "content",
        ),
      ],
      met: 4,
      total: 4,
    },
  },
  accuracy: {
    ok: true,
    data: {
      assertions: [
        assertion(
          "Example Studio is based in Austin, Texas.",
          "based in Austin, Texas",
          "Example Studio, Austin, Texas",
        ),
        assertion(
          "Example Studio is a brand identity studio.",
          "a brand identity studio",
          "We are a brand identity studio.",
        ),
        assertion("Example Studio was founded in 2012.", "founded in 2012", "Founded in 2012"),
      ],
      sources: [
        { domain: "example-studio.test", owner: "yours", because: "it is the site under audit" },
        { domain: "linkedin.com", owner: "platform", because: "a listing site" },
      ],
      siteFullyRead: true,
      pagesRead: PAGES.length,
      pagesTotal: PAGES.length,
      answersRead: 2,
      conflation: { detected: false, otherNames: [], engineQuote: null },
    },
  },
  analyze: {
    ok: true,
    data: {
      buyerQuestions: [
        question("What does this cost?", "Identity projects start at $12,000."),
        question(
          "Is this for someone like me?",
          "We work with founders launching a first product.",
        ),
        question(
          "Why should I believe you can do this?",
          "Forty identities since 2012, six of them for companies that went on to raise.",
        ),
        question(
          "Who will I actually be dealing with?",
          "You work directly with Sam and Priya, the two of us.",
        ),
        question("Where are you, and do you cover me?", "Austin, Texas, and remote across the US."),
        question(
          "What happens after I get in touch?",
          "We reply within one working day and book a 30-minute call.",
        ),
        question(
          "How long does a project like mine take?",
          "An identity takes eight to ten weeks.",
        ),
        question(
          "How do you work — what are the stages?",
          "Discovery, two rounds of concepts, then rollout.",
        ),
        question(
          "Is there a minimum size of project you take on?",
          "We do not take on projects under $12,000.",
        ),
        question("What will you need from me?", "About two hours a week from one decision-maker."),
      ],
      fixes: [
        {
          title: "Add a short case study for each of the three service lines",
          why: "The work page shows outcomes but the services page does not link to them, so a reader deciding between the three has to find the proof themselves.",
          impact: "medium",
          effort: "medium",
          tier: "content",
          origin: "recommendation",
        },
        {
          title: "Publish the answers to the ten buyer questions as a single FAQ page",
          why: "Every answer exists, spread over four pages. One page an assistant can quote whole is easier to cite than ten sentences it has to assemble.",
          impact: "medium",
          effort: "low",
          tier: "content",
          origin: "recommendation",
        },
      ],
      narrative: { findability: "", readability: "", answers: "" },
    },
  },
  probes: {
    ok: true,
    data: {
      answers: [
        {
          engine: "claude",
          query: "brand identity studio Austin",
          kind: "category",
          domainCited: true,
          brandMentioned: true,
          countedAsVisible: true,
          citedDomains: ["example-studio.test", "clutch.co", "designrush.com"],
          snippet: "Example Studio is a well-regarded identity studio in Austin…",
          truncated: true,
          askedAt: "2026-09-03T08:50:00.000Z",
        },
        {
          engine: "claude",
          query: "branding agency for a startup launching its first product",
          kind: "category",
          domainCited: false,
          brandMentioned: false,
          countedAsVisible: false,
          citedDomains: ["clutch.co", "designrush.com", "sortlist.com"],
          snippet: "Several studios specialise in launch identities…",
          truncated: true,
          askedAt: "2026-09-03T08:51:00.000Z",
        },
        {
          engine: "claude",
          query: "who is Example Studio",
          kind: "branded",
          domainCited: true,
          brandMentioned: true,
          countedAsVisible: true,
          citedDomains: ["example-studio.test", "linkedin.com"],
          snippet:
            "Example Studio is a brand identity studio based in Austin, Texas, founded in 2012…",
          truncated: true,
          askedAt: "2026-09-03T08:52:00.000Z",
        },
      ],
      visibilityScore: 50,
      brandedRecognized: true,
      competitorsSeen: [
        { domain: "clutch.co", count: 2 },
        { domain: "designrush.com", count: 2 },
        { domain: "sortlist.com", count: 1 },
      ],
      categoryProbes: { attempted: 2, answered: 2 },
      answerSpace: {
        answersWithCitations: 2,
        queriesAsked: 2,
        citationsTotal: 6,
        distinctDomains: 4,
        topSources: [
          { domain: "clutch.co", count: 2, share: 0.33 },
          { domain: "designrush.com", count: 2, share: 0.33 },
          { domain: "example-studio.test", count: 1, share: 0.17 },
          { domain: "sortlist.com", count: 1, share: 0.17 },
        ],
        domainsToHalf: 2,
        medianWidthPerAnswer: 3,
        ownDomainRank: 3,
        ownDomainCount: 1,
        topRival: { domain: "clutch.co", count: 2, share: 0.33 },
      },
    },
  },
};
