name: ci
on:
  pull_request:
  push:
    branches: [main]
jobs:
  ci:
    permissions:
      contents: read
      pull-requests: write
    uses: reddoorla/.github/.github/workflows/ci.yml@f812eac2dec6124a820f4854bb39527d323cae2e # pilot: feat/deploy-preview-comment
    with:
      node-version: "24"
      netlify-site: "reddoorla"
