name: renovate
on:
  schedule:
    - cron: "0 7 * * 1"
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: renovatebot/github-action@3064367f740a1a91cca218698a63902689cce200 # v46.1.20
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
